# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Haoyu Wang (Andrew)
description: Doctoral Student 
the University of Texas at Austin
logo: https://raw.githubusercontent.com/andrewhywong/andrewhywong.github.io/main/image/portraits.jpg
show_downloads: false
